[package]
name = "dictate"
version = "0.1.0"
edition = "2024"

[dependencies]
colored = "3.0.0"
reqwest = { version = "0.12", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

